# config/config.yaml
project: "fashion-mnist-feedforward"
entity: "me21b118-iit-madras"

data:
  batch_size: 64
  shuffle: True

model:
  input_dim: 784
  hidden_sizes: [128, 64]
  output_dim: 10
  activation: relu
  weight_init: xavier
  weight_decay: 0.0001

training:
  epochs: 10
  learning_rate: 0.001
  optimizer: adam
  seed: 42
  loss: cross_entropy
